# Generated by Django 2.2.10 on 2020-11-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'db_table': 'core_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('link_demo', models.URLField(blank=True, max_length=255, null=True, verbose_name='demo url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'diseño',
                'verbose_name_plural': 'diseños',
                'db_table': 'core_design',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='categoría')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'categoría de diseño',
                'verbose_name_plural': 'categorías de diseño',
                'db_table': 'core_designcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'categoría de usuario',
                'verbose_name_plural': 'categorías de usuario',
                'db_table': 'core_user_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='design_image/')),
                ('is_main_image', models.BooleanField(default=True, verbose_name='imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Design')),
            ],
            options={
                'verbose_name': 'imagen de diseño',
                'verbose_name_plural': 'imágenes de diseño',
                'db_table': 'core_design_image',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.ManyToManyField(to='core.DesignCategory', verbose_name='categoría'),
        ),
    ]
